
# L-System configuration

title    = "TEST"   # window title
axiom    = "F"      # starting string
angle    = 45       # turn angle in degree
distance = 20        # step length in pixels
max_iter = 6        # maximum iteration reachable with →
start_x  = 0
start_y  = -400
start_heading = 90

[rules]
F = "F-G-F"
