
# L-System configuration

title    = "TEST"   # window title
axiom    = "G"      # starting string
angle    = 45       # turn angle in degree
distance = 2        # step length in pixels
max_iter = 10        # maximum iteration reachable with →
start_x  = 0
start_y  = -400
start_heading = 90

[rules]
G = "FX"
X = "[+FX][-FX]"
F = "FF"
